// Generated by CoffeeScript 1.10.0
(function() {
  var fs, jsyaml;

  fs = require('fs');

  jsyaml = require('js-yaml');

  module.exports = {
    name: 'WithSchemaEditor config schema plugin',
    read_type: 'file',
    filters: function() {
      return [
        {
          name: 'JSON/YAML',
          extensions: ['json', 'yaml', 'yml']
        }, {
          name: 'すべてのファイル',
          extensions: ['*']
        }
      ];
    },
    load: function(app) {
      return app.editor().setValue(jsyaml.safeLoad(fs.readFileSync(app.target())));
    },
    save: function(app) {
      return fs.writeFileSync(app.target(), jsyaml.safeDump(app.editor().getValue()));
    },
    schema: function() {
      return {
        title: 'config',
        type: 'object',
        format: 'grid',
        properties: {
          target: {
            title: '対象ファイル/フォルダ',
            type: 'string'
          },
          schema: {
            title: 'スキーマプラグイン名',
            type: 'string'
          }
        }
      };
    }
  };

}).call(this);
