// Generated by CoffeeScript 1.10.0
(function() {
  var fs, jsyaml;

  fs = require('fs');

  jsyaml = require('js-yaml');

  module.exports = {
    name: 'WithSchemaEditor config schema plugin',
    read_type: 'file',
    filters: function() {
      return [
        {
          name: 'JSON/YAML',
          extensions: ['json', 'yaml', 'yml']
        }, {
          name: 'すべてのファイル',
          extensions: ['*']
        }
      ];
    },
    read: function(file, editor) {
      this.file = file;
      return jsyaml.safeLoad(fs.readFileSync(file));
    },
    oneditor: function(editor) {
      return editor.on('change', (function(_this) {
        return function() {
          return fs.writeFileSync(_this.file, jsyaml.safeDump(editor.getValue()));
        };
      })(this));
    },
    schema: function() {
      return {
        title: 'config',
        type: 'object',
        format: 'grid',
        properties: {
          target: {
            title: '対象ファイル/フォルダ',
            type: 'string'
          },
          schema: {
            title: 'スキーマプラグイン名',
            type: 'string'
          }
        }
      };
    }
  };

}).call(this);
